### ISSUE TITLE
Iyte extract course detail page bug

### ISSUE THREAD

**Issue by okanwyl** [okanwyl/uniparser#9]
<img width="608" alt="image" src="https://user-images.githubusercontent.com/100314334/216080787-4414a760-8a5a-475d-87a5-d7d8a98c322c.png">

**Comment by OktayKaloglu** [comment]
bende o hata yok

**Comment by OktayKaloglu** [comment]
gördüm bakıyorum

**Comment by OktayKaloglu** [comment]
![image](https://user-images.githubusercontent.com/101494182/216083654-5380f6c9-4488-4573-9408-886ba4dd50af.png)
3 hoca var
